apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3-bucket-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Haliltarik/poc-crossplane-helm.git
    targetRevision: main
    path: apps/s3-bucket-test
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
