apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: composites3buckets.aws.engie.com
spec:
  group: aws.engie.com
  names:
    kind: CompositeS3Bucket
    plural: composites3buckets
  claimNames:
    kind: S3Bucket
    plural: s3buckets
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - bucketName
                - region
                - tags
              properties:
                bucketName:
                  type: string
                region:
                  type: string
                tags:
                  type: array
                  items:
                    type: object
                    required:
                      - key
                      - value
                    properties:
                      key:
                        type: string
                      value:
                        type: string
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: crossplane-contrib-function-patch-and-transform
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.6.0
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: crossplane-contrib-function-go-templating
  namespace: crossplane-system
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.5.0
---
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3bucket-default
  namespace: crossplane-system
spec:
  compositeTypeRef:
    apiVersion: aws.engie.com/v1alpha1
    kind: CompositeS3Bucket
  mode: Pipeline
  pipeline:
    - step: render-s3
      functionRef:
        name: crossplane-contrib-function-go-templating
      input:
        apiVersion: gotemplate.fn.crossplane.io/v1beta1
        kind: GoTemplate
        templates:
          - base:
              apiVersion: s3.aws.crossplane.io/v1beta1
              kind: Bucket
              metadata:
                name: {{ .observed.composite.spec.bucketName }}
              spec:
                forProvider:
                  locationConstraint: {{ .observed.composite.spec.region }}
                  serverSideEncryptionConfiguration:
                    rules:
                      - applyServerSideEncryptionByDefault:
                          sseAlgorithm: AES256
                  tagging:
                    tagSet:
                      - key: Name
                        value: {{ (index .observed.composite.spec.tags 0).value }}
                      - key: ApplicationId
                        value: {{ (index .observed.composite.spec.tags 1).value }}
                      - key: CostCenter
                        value: {{ (index .observed.composite.spec.tags 2).value }}
                      - key: Environment
                        value: {{ (index .observed.composite.spec.tags 3).value }}
                  policy: |
                    {
                      "Version": "2012-10-17",
                      "Statement": [
                        {
                          "Sid": "enforce-tls-12-requests-only",
                          "Effect": "Deny",
                          "Principal": { "AWS": "*" },
                          "Action": "*",
                          "Resource": [
                            "arn:aws:s3:::{{ .observed.composite.spec.bucketName }}/*",
                            "arn:aws:s3:::{{ .observed.composite.spec.bucketName }}"
                          ],
                          "Condition": {
                            "NumericLessThan": { "s3:TlsVersion": "1.2" }
                          }
                        },
                        {
                          "Sid": "enforce-tls-requests-only",
                          "Effect": "Deny",
                          "Principal": { "AWS": "*" },
                          "Action": "*",
                          "Resource": [
                            "arn:aws:s3:::{{ .observed.composite.spec.bucketName }}/*",
                            "arn:aws:s3:::{{ .observed.composite.spec.bucketName }}"
                          ],
                          "Condition": {
                            "Bool": { "aws:SecureTransport": "false" }
                          }
                        }
                      ]
                    }
                providerConfigRef:
                  name: default
                deletionPolicy: Delete
