apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: composites3buckets.aws.engie.com
spec:
  group: aws.engie.com
  names:
    kind: CompositeS3Bucket
    plural: composites3buckets
  claimNames:
    kind: S3Bucket
    plural: s3buckets
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - bucketName
                - region
                - tags
              properties:
                bucketName:
                  type: string
                region:
                  type: string
                tags:
                  type: object
                  required:
                    - Name
                    - ApplicationId
                    - CostCenter
                    - Environment
                  properties:
                    Name:
                      type: string
                    ApplicationId:
                      type: string
                    CostCenter:
                      type: string
                    Environment:
                      type: string

